name: facebook_setup
description: A new Flutter package project.
version: 0.0.1
homepage: "PUT HOMEPAGE HERE"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
#  flutter:
#    sdk: flutter
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.0
  xml: ^5.3.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.20.1
  flutter_lints: ^1.0.4
